replicaCount: 1

image:
  repository: redis
  tag: 4.0.10
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379


resources:
  limits:
    memory: "20M"
    cpu: "50m"
  requests:
    memory: "10M"
    cpu: "8m"

nodeSelector: {}

tolerations: []

affinity: {}
