replicaCount: 1

image:
  repository: mongo
  tag: 3.6.5-jessie
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017


resources:
  limits:
    memory: "1000M"
    cpu: "500m"
  requests:
    memory: "50M"
    cpu: "10m"

nodeSelector: {}

tolerations: []

affinity: {}
