replicaCount: 1

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5672


resources:
  limits:
    memory: "1000M"
    cpu: "500m"
  requests:
    memory: "100M"
    cpu: "50m"

nodeSelector: {}

tolerations: []

affinity: {}
